@startuml DC
class Anak {
  - nama: String
  - tanggalLahir: Date = null
  - alamat: String
  - orangTua: wali [1..1] = null
  + void daftarAnak()
  + void perbaruiData()
}

class wali {
  - nama: String
  - alamat: String
  - nomorTelepon: String
  - anak: List<Anak> [0..*] = new ArrayList<>()
  + void daftarOrangTua()
  + void perbaruiData()
}

class Staf {
  - nama: String
  - posisi: String
  - jadwalKerja: String
  + void perbaruiData()
  + void kelolaJadwal()
  + void kelolaDataStaf()
  + void kelolaDataOrangTua()
}

class Jadwal {
  - tanggal: Date = null
  - kegiatan: String
  - staf: List<Staf> [0..*] = new ArrayList<>()
  + void kelolaJadwal()
}

class Laporan {
  - tanggal: Date = null
  - jenis: String
  - isi: String
  + void lihatLaporan()
}

Anak --> "1..1" wali
wali --> "0..*" Anak
Jadwal --> "0..*" Staf
Staf --> "0..*" Jadwal
Staf --> "0..*" Staf
Staf --> "0..*" wali
Staf --> "0..*" Laporan
wali --> "0..*" Laporan
@enduml
